AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - '/script/**/**/*'
    - 'spec/**/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 20
